"""
# Global constants and paths.

* Description:

    All non-dynamic, or fixed, values and paths for the core pipeline.
"""


import enum
import getpass
import sys
from pathlib import Path

import lucid.core


# ----------Repo---------------------------------------------------------------

PYTHON_EXEC = Path(sys.executable)
VENV_SITE_PACKAGES_PATH = Path(PYTHON_EXEC.parent.parent, 'Lib/site-packages')

try:
    LUCID_REPO_PATH = Path(lucid.core.__file__).parent.parent.parent
except TypeError:
    # Local editable installations return None for module.__file__
    # noinspection PyUnresolvedReferences
    LUCID_REPO_PATH = Path(lucid.core.__spec__.submodule_search_locations._path[0])

LUCID_PATH = Path(LUCID_REPO_PATH, 'lucid')

NETWORK_DRIVE_ROOT = Path('T:/')

VERSION_PADDING = 3

UNASSIGNED = 'UNASSIGNED'
"""A None-like value for when None is not a good idea to use, or semantically
it would be better to specify unassigned values rather than uninitialized
values.
"""


# ----------User---------------------------------------------------------------

USERNAME = getpass.getuser()

USER_PIPE_DIR = Path(LUCID_PATH, 'user')
"""The directory for all user specific settings. Exists in .gitignore."""

USER_SETTINGS_FILE = Path(USER_PIPE_DIR, 'user_settings.json')
"""The user_settings json file path for the user settings menu in the
launcher.
"""

USER_LOG_DIR = Path(USER_PIPE_DIR, 'logs')
"""Log files, typically in the form of jsons, are stored here. Logs can be
generated by an exception tracker, telemetry, or other systems.
"""


# ----------Environment--------------------------------------------------------

ENV_PROJECT = 'ENV_PROJECT'


# ----------Project------------------------------------------------------------

PROJECTS_PATH = Path(NETWORK_DRIVE_ROOT, 'projects')
"""The 'root' projects path to where all projects are stored."""


# ----------Applications-------------------------------------------------------

@enum.unique
class DCCs(enum.Enum):
    MAYA = 'MAYA'
    PAINTER = 'PAINTER'
    DESIGNER = 'DESIGNER'
    UNREAL = 'UNREAL'
