"""
# Lucid Project Management

* Description:

    Herein are paths at the project level. This library is similar to constants
    but is filled with paths that require the show name, via config.Config.
"""


from pathlib import Path

from lucid.core import const
from lucid.core.config import Config


PROJECT_ROOT = Path(const.PROJECTS_DIR, Config.project)
"""The root dir of the currently loaded project."""


# --------General--------------------------------------------------------------

CONFIG_DIR = Path(PROJECT_ROOT, 'config')
"""The root config directory of the currently loaded project."""

DATABASE_DIR = Path(PROJECT_ROOT, 'database')
"""The root dir for all project related database files."""

PROJECT_USER_DIR = Path(PROJECT_ROOT, 'user')
"""A mini-home for artists bound to the project's directory structure."""


# --------Asset----------------------------------------------------------------

ASSET_DIR = Path(PROJECT_ROOT, 'asset')
"""The root dir of the assets folder on the currently loaded project."""

ASSET_DB_FILE = Path(DATABASE_DIR, 'asset.db')
"""The primary asset database file."""


# --------Engine---------------------------------------------------------------

ENGINE_DIR = Path(PROJECT_ROOT, 'engine')
"""The engine related files for the currently loaded project.
These are not files located in the source control tracked engine project, but
rather files related to the engine project.
"""

ENGINE_OUTGOING_DIR = Path(ENGINE_DIR, 'outgoing')
"""Files generated by the engine that are not to remain in engine, e.g.
cutscene renders, sim exports, etc.
"""

ENGINE_RENDERS_DIR = Path(ENGINE_OUTGOING_DIR, 'renders')
"""Directory for renders that came out of the engine."""

ENGINE_SIM_DIR = Path(ENGINE_OUTGOING_DIR, 'sim')
"""Directory for exported sims that came out of the engine."""
