"""
# Lucid Project Management

* Description:

    Herein are paths at the project level. This library is similar to constants
    but is filled with paths that require the show name, via config.Config.
"""


import types
import sys
from pathlib import Path

from lucid.core import const
from lucid.core.config import Config


class ProjectPaths(types.ModuleType):
    # Exists to create dynamic variables at the module level.
    # At various points in the pipeline we may want to import this but not
    # reference any vars until after we have set the project.
    # This requires us to dynamically update all the paths.

    def __init__(self, name: str) -> None:
        super().__init__(name)

    @property
    def project_root(self) -> Path:
        return Path(const.PROJECTS_DIR, Config.project)

    @property
    def config_dir(self) -> Path:
        return Path(project_root, 'config')

    @property
    def database_dir(self) -> Path:
        return Path(project_root, 'database')

    @property
    def user_dir(self) -> Path:
        return Path(project_root, 'user')

    @property
    def asset_dir(self) -> Path:
        return Path(project_root, 'asset')

    @property
    def asset_db_file(self) -> Path:
        return Path(database_dir, 'asset.db')

    @property
    def engine_dir(self) -> Path:
        return Path(project_root, 'engine')

    @property
    def engine_outgoing_dir(self) -> Path:
        return Path(engine_dir, 'outgoing')

    @property
    def engine_renders_dir(self) -> Path:
        return Path(engine_outgoing_dir, 'renders')

    @property
    def engine_sim_dir(self) -> Path:
        return Path(engine_outgoing_dir, 'sim')


# This is here to make each var dynamic at module level.
custom_modules = ProjectPaths(sys.modules[__name__].__name__)
sys.modules[__name__] = custom_modules


'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Required for static type checkers to accept these names as members of this module
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

project_root: Path
"""The root dir of the currently loaded project."""


# --------General--------------------------------------------------------------

config_dir: Path
"""The root config directory of the currently loaded project."""

database_dir: Path
"""The root dir for all project related database files."""

user_dir: Path
"""A mini-home for artists bound to the project's directory structure."""


# --------Asset----------------------------------------------------------------

asset_dir: Path
"""The root dir of the assets folder on the currently loaded project."""

asset_db_file: Path
"""The primary asset database file."""


# --------Engine---------------------------------------------------------------

engine_dir: Path
"""The engine related files for the currently loaded project.
These are not files located in the source control tracked engine project, but
rather files related to the engine project.
"""

engine_outgoing_dir: Path
"""Files generated by the engine that are not to remain in engine, e.g.
cutscene renders, sim exports, etc.
"""

engine_renders_dir: Path
"""Directory for renders that came out of the engine."""

engine_sim_dir: Path
"""Directory for exported sims that came out of the engine."""
