"""
# Asset Pipeline Class

* Description:

    The base for all asset related pipelines. An 'asset' is any content file
    generated by artists. These could be models, rigs, shaders, textures,
    animations, grooms, cutscene shots, layouts, etc.

    Assets pipeline will need two primary responsibilities: writing to disk,
    and registering in a database. Each task may come with various sub-steps,
    such as path or name generation.
"""


import enum
from dataclasses import dataclass
from typing import Optional

import lucid.core.work
from lucid.core import const
from lucid.core import details
from lucid.core.pipeline.base import BasePipeline


@enum.unique
class Hook(enum.Enum):
    """Most common file io hook types."""
    PRE_PUBLISH = 'pre_publish'
    POST_PUBLISH = 'post_publish'
    PRE_OPEN = 'pre_open'
    POST_OPEN = 'post_open'
    PRE_IMPORT = 'pre_import'
    POST_IMPORT = 'post_import'


@dataclass
class AssetDetails(details.DomainDetails):
    """Any file that would make its way into engine or shot files."""
    # spaceship_damaged_v001.fbx
    base_name: str = const.UNASSIGNED
    variation: str = const.UNASSIGNED
    version: Optional[int] = None
    file_type: str = const.UNASSIGNED


class AssetPipeline(BasePipeline):
    """Base asset pipeline for all pipeline objects that write out a file."""

    _hooks = {
        Hook.PRE_PUBLISH.value: [],
        Hook.POST_PUBLISH.value: [],
        Hook.PRE_OPEN.value: [],
        Hook.POST_OPEN.value: [],
        Hook.PRE_IMPORT.value: [],
        Hook.POST_IMPORT.value: []
    }

    # --------File IO Methods--------------------------------------------------

    @classmethod
    def publish_file(cls, unit: lucid.core.work.WorkUnit) -> None:
        """Publish a file using domain-specific logic, then register
        it in the database.
        """
        cls.log_with_context(unit, 'Preprocessing publish')
        cls.run_hooks(Hook.PRE_PUBLISH.value, unit)

        cls.log_with_context(unit, 'Publishing')
        cls.dcc_publish(unit)
        cls.log_with_context(unit, 'Registering')
        cls.register_in_database(unit)

        cls.log_with_context(unit, 'Postprocessing publish')
        cls.run_hooks(Hook.POST_PUBLISH.value, unit)

        cls.log_with_context(unit, 'Publish complete.')

    @classmethod
    def open_file(cls, unit: lucid.core.work.WorkUnit) -> None:
        """Open a file using the application's API."""
        cls.log_with_context(unit, 'Opening unit')
        cls.run_hooks(Hook.PRE_OPEN.value, unit)
        cls.dcc_open(unit)
        cls.run_hooks(Hook.POST_OPEN.value, unit)
        cls.log_with_context(unit, 'Unit opened')

    @classmethod
    def import_file(cls, unit: lucid.core.work.WorkUnit) -> None:
        """Import a file using the application's API."""
        cls.log_with_context(unit, 'Importing unit')
        cls.run_hooks(Hook.PRE_IMPORT.value, unit)
        cls.dcc_import(unit)
        cls.run_hooks(Hook.POST_IMPORT.value, unit)
        cls.log_with_context(unit, 'Unit imported')

    # --------Derived Methods--------------------------------------------------

    @classmethod
    def register_in_database(cls, unit: lucid.core.work.WorkUnit) -> None:
        """Override to specify how a given file becomes registered in a
        corresponding database.
        """
        raise NotImplemented

    @classmethod
    def dcc_publish(cls, unit: lucid.core.work.WorkUnit) -> None:
        """Override to specify how a given DCC publishes a file."""
        raise NotImplemented

    @classmethod
    def dcc_open(cls, unit: lucid.core.work.WorkUnit) -> None:
        """Override to specify how a given DCC opens a file."""
        raise NotImplemented

    @classmethod
    def dcc_import(cls, unit: lucid.core.work.WorkUnit) -> None:
        """Override to specify how a given DCC imports a file."""
        raise NotImplemented
